name: Build .NET Service

on:
  push:
    branches: [ main ]    
    paths:
        - 'Sandwitch.Service/**'

  pull_request:
    branches: [ main ]
    paths:
        - 'Sandwitch.Service/**'

permissions:
  contents: read  

defaults:
  run:
    working-directory: Sandwitch.Service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v5

      - name: ğŸ› ï¸ Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: ğŸ“¥ Restore dependencies
        run: dotnet restore --locked-mode Sandwitch.Service/Sandwitch.Service.csproj 

      - name: â™»ï¸ Clean project
        run: dotnet clean  Sandwitch.Service/Sandwitch.Service.csproj 

      - name: ğŸ—ï¸ Build project
        run: dotnet build --no-restore Sandwitch.Service/Sandwitch.Service.csproj